run_tag: '2048'
env_config: {
  env_type: '2048'
}
model_config: { # overwritten if loading a checkpoint
  res_channels: 16,
  res_blocks: 6,
  kernel_size: 3,
  value_fc_size: 32,
  value_output_activation: ""
}
train_mode_config: {
  algo_config: {
    name: 'lazyzero',
    temperature: 1.0,
    num_policy_rollouts: 500, 
    rollout_depth: 3, 
    puct_coeff: 1.0 
  },
  learning_rate: 0.1,
  momentum: 0.8,
  c_reg: 0.0001,
  replay_memory_max_size: 20000,
  replay_memory_min_size: 20000,
  parallel_envs: 8192,
  policy_factor: 1.0,
  minibatch_size: 4096,
  episodes_per_epoch: 20000,
  episodes_per_minibatch: 1,
  test_config: {
      algo_config: {
      name: 'lazyzero',
      temperature: 0.0,
      num_policy_rollouts: 500, 
      rollout_depth: 3, 
      puct_coeff: 1.0 
    },
    episodes_per_epoch: 1000
  }
}
test_mode_config: {
    algo_config: {
      name: 'lazyzero',
      temperature: 0.0,
      num_policy_rollouts: 500, 
      rollout_depth: 3, 
      puct_coeff: 1.0 
    },
  episodes_per_epoch: 1000
}



